
DROP DATABASE IF EXISTS leaderboards;
CREATE DATABASE leaderboards;

USE leaderboards;

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) UNIQUE NOT NULL,
    pass VARCHAR(30) NOT NULL
);

CREATE TABLE scores (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) UNIQUE NOT NULL,
    score INT NOT NULL
    REFERENCES users(username)
);










